### ISSUE TITLE
New deposit

### ISSUE THREAD

**Issue by webparadoxer** [zhouaini528/coinbase-php#1]
Hi.

I want to transfer/deposit money from attached paypal account to coinbase. But all api methods dont work.

Get payment ID 
```
$result = $coinbase->privates()->getPaymentMethods([
       'account_id' => ID,
    ]);
```

```
"label": "Daily PayPal limit"
[primary_buy] => 1
                    [primary_sell] => 
                    [instant_buy] => 1
                    [instant_sell] => 1
```

Make buy/deposit methods. Deposit return - Can't deposit with this account

Buy method - return operation ID, but
```
    $result = $coinbase->privates()->getAccountBuys([
        'account_id' => ID,
    ]);
    print_r($result);


      "status": "canceled", 
```

How can i do it?!

**Comment by zhouaini528** [comment]
I'm sorry I don't know how to solve it. You should look at the documentation more, you can also look at the [code](https://github.com/zhouaini528/coinbase-php/blob/master/src/Api/Coinbase/Privates.php), and search for whether the interface matches the documentation
